module RubyLsp
  class Addon
  end

  class GlobalState
    attr_reader workspace_path: String
  end

  class Message
  end

  class Notification < Message
    def self.window_log_message: (String message, ?type: Integer) -> Notification
  end
end
