AllCops:
  Exclude:
    - "spec/test-app/**/*"
    - "vendor/bundle/**/*"
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
